matrix:
  include:
    - language: go
      go: 1.13.x
      install: true
      script:
        - ./test.sh
      deploy:
        # deploy binaries
        - provider: script
          skip_cleanup: true
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux

        # deploy API
        - provider: heroku
          api_key: $HEROKU_PRODUCTION_API_KEY
          app: $HEROKU_APP_NAME
          on:
            tags: true
        
    - language: node_js
      node_js: 7
      script:
        npm i -g @stoplight/cli
      deploy:
        # deploy docs
        - provider: script
          skip_cleanup: true
          script: stoplight publish --token $SPOTLIGHT_TOKEN --url https://stoplight.io/api
          on:
            tags: true
        

notifications:
  email: false
